# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\frame.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(696, 822)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(250, 750, 150, 46))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(140, 30, 161, 691))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        QtWidgets.QLabel('''font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);''')
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(340, 20, 181, 721))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_2.addWidget(self.lineEdit_5)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_2.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_2.addWidget(self.lineEdit_8)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_2.addWidget(self.lineEdit_9)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_2.addWidget(self.lineEdit_10)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_2.addWidget(self.lineEdit_6)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "开始训练"))
        self.pushButton.setStyleSheet('font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);')
        self.label.setText(_translate("Form", "dropout:"))
        self.label.setStyleSheet('font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);')
        self.label_2.setText(_translate("Form", "num_classes:"))
        self.label_2.setStyleSheet('font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);')
        self.label_3.setText(_translate("Form", "n_vocab:"))
        self.label_3.setStyleSheet('font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);')
        self.label_4.setStyleSheet('font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);')
        self.label_4.setText(_translate("Form", "num_epoches:"))
        self.label_5.setText(_translate("Form", "batch_size:"))
        self.label_5.setStyleSheet('font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);')
        self.label_6.setText(_translate("Form", "pad_size:"))
        self.label_6.setStyleSheet('font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);')
        self.label_7.setText(_translate("Form", "learning_rate:"))
        self.label_7.setStyleSheet('font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);')
        self.label_8.setText(_translate("Form", "embed_size:"))
        self.label_8.setStyleSheet('font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);')
        self.label_9.setText(_translate("Form", "hidden_size:"))
        self.label_9.setStyleSheet('font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);')
        self.label_10.setText(_translate("Form", "num_lays:"))
        self.label_10.setStyleSheet('font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);')
        self.lineEdit.setText(_translate("Form", "0.1"))
        self.lineEdit.setStyleSheet('font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);')
        self.lineEdit_2.setText(_translate("Form", "100"))
        self.lineEdit_2.setStyleSheet('font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);')
        self.lineEdit_5.setText(_translate("Form", "11"))
        self.lineEdit_5.setStyleSheet('font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);')
        self.lineEdit_7.setText(_translate("Form", "1000"))
        self.lineEdit_7.setStyleSheet('font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);')
        self.lineEdit_8.setText(_translate("Form", "100"))
        self.lineEdit_8.setStyleSheet('font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);')
        self.lineEdit_9.setText(_translate("Form", "20"))
        self.lineEdit_9.setStyleSheet('font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);')
        self.lineEdit_3.setText(_translate("Form", "0.0001"))
        self.lineEdit_3.setStyleSheet('font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);')
        self.lineEdit_10.setText(_translate("Form", "120"))
        self.lineEdit_10.setStyleSheet('font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);')
        self.lineEdit_6.setText(_translate("Form", "50"))
        self.lineEdit_6.setStyleSheet('font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);')
        self.lineEdit_4.setText(_translate("Form", "20"))
        self.lineEdit_4.setStyleSheet('font: 18pt \"微软雅黑\";background-color: rgb(245, 245, 245);')

import sys
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
